server:
  port: 8020
spring:
  application:
    name: eleme-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
